name: Sync Leetcode

on:
  workflow_dispatch:     # इससे आप जब चाहें खुद बटन दबाकर सिंक कर सकते हैं
  schedule:
    - cron: '0 8 * * *'  # यह हर दिन अपने आप रन होगा

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: LeoCen/leetcode-sync@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-submissions
